# Generated by Django 4.2 on 2023-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workOrder', models.CharField(max_length=125, null=True, verbose_name='Work Order')),
                ('equipmentName', models.CharField(max_length=125, null=True, verbose_name='Equipment Name')),
                ('compleateDate', models.DateField(null=True, verbose_name='Compleate Date')),
            ],
        ),
    ]
