# Generated by Django 4.2 on 2023-08-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionShortName', models.CharField(max_length=125, null=True, verbose_name='Action Short Name')),
                ('actionCode', models.CharField(max_length=125, null=True, verbose_name='Action Code')),
            ],
        ),
        migrations.CreateModel(
            name='CauseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causeShortName', models.CharField(max_length=125, null=True, verbose_name='Cause Short Name')),
                ('causeCode', models.CharField(max_length=125, null=True, verbose_name='Cause Code')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentName', models.CharField(max_length=125, null=True, verbose_name='Equipment Name')),
            ],
        ),
        migrations.CreateModel(
            name='FailureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureShortName', models.CharField(max_length=125, null=True, verbose_name='Failure Short Name')),
                ('failureCode', models.CharField(max_length=125, null=True, verbose_name='Failure Code')),
                ('equipmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.equipmentname')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workOrder', models.CharField(max_length=125, null=True, verbose_name='Work Order')),
                ('serialNumber', models.CharField(max_length=125, null=True, verbose_name='Serial Number')),
                ('compleateDate', models.DateField(null=True, verbose_name='Compleate Date')),
                ('remark', models.CharField(blank=True, max_length=125, null=True, verbose_name='Remark')),
                ('actionCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.actioncode')),
                ('causeCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.causecode')),
                ('equipmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.equipmentname')),
                ('failureCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.failurecode')),
            ],
        ),
        migrations.AddField(
            model_name='causecode',
            name='equipmentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.equipmentname'),
        ),
        migrations.AddField(
            model_name='actioncode',
            name='equipmentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.equipmentname'),
        ),
    ]
